"""add_kyc_land_verification_and_project_lifecycle

Revision ID: 485a45c7bb2c
Revises: ffe795a51f3b
Create Date: 2026-05-19 13:50:26.648681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485a45c7bb2c'
down_revision: Union[str, Sequence[str], None] = 'ffe795a51f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_verifications_id'), 'kyc_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_kyc_verifications_status'), 'kyc_verifications', ['status'], unique=False)
    op.create_index(op.f('ix_kyc_verifications_user_id'), 'kyc_verifications', ['user_id'], unique=False)
    op.create_table('land_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('document_url', sa.String(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_land_verifications_id'), 'land_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_land_verifications_project_id'), 'land_verifications', ['project_id'], unique=False)
    op.create_index(op.f('ix_land_verifications_verification_status'), 'land_verifications', ['verification_status'], unique=False)
    # Add lifecycle_status as nullable first to avoid NOT NULL violation on existing rows
    op.add_column('projects', sa.Column('lifecycle_status', sa.String(), nullable=True))
    # Backfill all existing rows with a sensible default
    op.execute("UPDATE projects SET lifecycle_status = 'submitted' WHERE lifecycle_status IS NULL")
    # Now enforce NOT NULL
    op.alter_column('projects', 'lifecycle_status', nullable=False)
    op.add_column('projects', sa.Column('credits_issued', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('credits_issued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('issued_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_projects_lifecycle_status'), 'projects', ['lifecycle_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_lifecycle_status'), table_name='projects')
    op.drop_column('projects', 'issued_by')
    op.drop_column('projects', 'credits_issued_at')
    op.drop_column('projects', 'credits_issued')
    op.drop_column('projects', 'lifecycle_status')
    op.drop_index(op.f('ix_land_verifications_verification_status'), table_name='land_verifications')
    op.drop_index(op.f('ix_land_verifications_project_id'), table_name='land_verifications')
    op.drop_index(op.f('ix_land_verifications_id'), table_name='land_verifications')
    op.drop_table('land_verifications')
    op.drop_index(op.f('ix_kyc_verifications_user_id'), table_name='kyc_verifications')
    op.drop_index(op.f('ix_kyc_verifications_status'), table_name='kyc_verifications')
    op.drop_index(op.f('ix_kyc_verifications_id'), table_name='kyc_verifications')
    op.drop_table('kyc_verifications')
    # ### end Alembic commands ###
