"""Add polygon coordinates and simplify project structure

Revision ID: a826e5a1b6a7
Revises: bed847110c52
Create Date: 2026-05-18 12:38:40.916555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a826e5a1b6a7'
down_revision: Union[str, Sequence[str], None] = 'bed847110c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('polygon_coordinates', sa.Text(), nullable=True))
    op.drop_column('projects', 'project_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('projects', 'polygon_coordinates')
    # ### end Alembic commands ###
