"""Add GIS analytics fields to projects

Revision ID: bd6ae18deda1
Revises: 3ae26b7d4622
Create Date: 2026-05-18 00:44:09.799782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6ae18deda1'
down_revision: Union[str, Sequence[str], None] = '3ae26b7d4622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('ndvi_score', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('vegetation_health', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('fraud_risk_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'fraud_risk_score')
    op.drop_column('projects', 'vegetation_health')
    op.drop_column('projects', 'ndvi_score')
    # ### end Alembic commands ###
