"""Add biomass analytics fields to projects

Revision ID: d575a320f809
Revises: a826e5a1b6a7
Create Date: 2026-05-18 14:49:39.380843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd575a320f809'
down_revision: Union[str, Sequence[str], None] = 'a826e5a1b6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_type', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('agb_per_hectare', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('total_biomass', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('carbon_stock', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('co2e', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'co2e')
    op.drop_column('projects', 'carbon_stock')
    op.drop_column('projects', 'total_biomass')
    op.drop_column('projects', 'agb_per_hectare')
    op.drop_column('projects', 'project_type')
    # ### end Alembic commands ###
