"""Add audit logs and credit ownerships

Revision ID: f5bab4071718
Revises: e91d4a7f3c6b
Create Date: 2026-05-19 01:46:24.427446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5bab4071718'
down_revision: Union[str, Sequence[str], None] = 'e91d4a7f3c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True, comment='ID of the Admin or Auditor performing the action'),
    sa.Column('target_id', sa.UUID(), nullable=True, comment='ID of the project or user being audited'),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('blockchain_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_table('credit_ownerships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('total_credits_owned', sa.Float(), nullable=False),
    sa.Column('credits_retired', sa.Float(), nullable=False),
    sa.Column('last_purchase_id', sa.UUID(), nullable=True),
    sa.Column('blockchain_reference', sa.String(), nullable=True, comment='Blockchain token ID or specific metadata'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['last_purchase_id'], ['purchases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'project_id', name='uix_owner_project_portfolio')
    )
    op.create_index(op.f('ix_credit_ownerships_id'), 'credit_ownerships', ['id'], unique=False)
    op.create_index(op.f('ix_credit_ownerships_owner_id'), 'credit_ownerships', ['owner_id'], unique=False)
    op.create_index(op.f('ix_credit_ownerships_project_id'), 'credit_ownerships', ['project_id'], unique=False)
    op.add_column('purchases', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.add_column('purchases', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    op.add_column('purchases', sa.Column('payment_status', sa.String(), server_default='pending', nullable=False))
    op.add_column('purchases', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('purchases', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Total INR amount',
               existing_nullable=False)
    op.alter_column('purchases', 'status',
               existing_type=sa.VARCHAR(),
               server_default='completed',
               nullable=False)
    op.create_index(op.f('ix_purchases_razorpay_order_id'), 'purchases', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_purchases_razorpay_payment_id'), 'purchases', ['razorpay_payment_id'], unique=False)
    op.alter_column('transactions', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.VARCHAR(),
               comment='credit_purchase | credit_mint | credit_transfer | credit_retirement',
               existing_nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Total INR amount',
               existing_nullable=False)
    op.add_column('wallets', sa.Column('carbon_balance', sa.Float(), server_default='0', nullable=False, comment='Current spendable/owned credits'))
    op.add_column('wallets', sa.Column('total_purchased', sa.Float(), server_default='0', nullable=False))
    op.add_column('wallets', sa.Column('total_retired', sa.Float(), server_default='0', nullable=False))
    op.add_column('wallets', sa.Column('wallet_address', sa.String(), nullable=True))
    op.add_column('wallets', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('wallets', sa.Column('last_blockchain_sync', sa.DateTime(timezone=True), nullable=True))
    op.add_column('wallets', sa.Column('currency', sa.String(), server_default='INR', nullable=False))
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    op.create_index(op.f('ix_wallets_wallet_address'), 'wallets', ['wallet_address'], unique=False)
    op.drop_column('wallets', 'crypto_wallet_address')
    op.drop_column('wallets', 'crypto_network')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('crypto_network', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('wallets', sa.Column('crypto_wallet_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_wallets_wallet_address'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.drop_column('wallets', 'currency')
    op.drop_column('wallets', 'last_blockchain_sync')
    op.drop_column('wallets', 'is_verified')
    op.drop_column('wallets', 'wallet_address')
    op.drop_column('wallets', 'total_retired')
    op.drop_column('wallets', 'total_purchased')
    op.drop_column('wallets', 'carbon_balance')
    op.alter_column('transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Total INR amount',
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='credit_purchase | credit_mint | credit_transfer | credit_retirement',
               existing_nullable=False)
    op.alter_column('transactions', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_purchases_razorpay_payment_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_razorpay_order_id'), table_name='purchases')
    op.alter_column('purchases', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('purchases', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Total INR amount',
               existing_nullable=False)
    op.drop_column('purchases', 'updated_at')
    op.drop_column('purchases', 'payment_status')
    op.drop_column('purchases', 'razorpay_payment_id')
    op.drop_column('purchases', 'razorpay_order_id')
    op.drop_index(op.f('ix_credit_ownerships_project_id'), table_name='credit_ownerships')
    op.drop_index(op.f('ix_credit_ownerships_owner_id'), table_name='credit_ownerships')
    op.drop_index(op.f('ix_credit_ownerships_id'), table_name='credit_ownerships')
    op.drop_table('credit_ownerships')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
