from pydantic import BaseModel
from uuid import UUID
from datetime import datetime


class ProjectBase(BaseModel):
    project_name: str
    project_type: str | None = None

    location: str
    country: str = "India"

    # POLYGON GEOJSON / JSON STRING
    polygon_coordinates: str | None = None

    # AUTO-GENERATED BY BACKEND
    latitude: float | None = None
    longitude: float | None = None
    land_area_acres: float | None = None

    description: str | None = None


class ProjectCreate(ProjectBase):
    pass


class ProjectUpdate(BaseModel):
    project_name: str | None = None
    project_type: str | None = None
    location: str | None = None
    country: str | None = None

    polygon_coordinates: str | None = None

    description: str | None = None


class ProjectResponse(ProjectBase):
    id: UUID
    owner_id: UUID

    satellite_status: str
    audit_status: str

    ndvi_score: float
    vegetation_health: float
    fraud_risk_score: float

    estimated_annual_credits: float
    first_issuance_credits: float
    estimated_credits: int
    total_credits_generated: float
    credits_available: float
    credits_sold: float
    price_per_credit: float
    credit_currency: str

    status: str

    tokenized: bool
    blockchain_tx_hash: str | None = None

    verification_notes: str | None = None

    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True
